parameters:
    open_orchestra_backoffice.type.template.class: OpenOrchestra\BackofficeBundle\Form\Type\TemplateType
    open_orchestra_backoffice.type.node.class: OpenOrchestra\BackofficeBundle\Form\Type\NodeType
    open_orchestra_backoffice.type.area.class: OpenOrchestra\BackofficeBundle\Form\Type\AreaType
    open_orchestra_backoffice.type.block.class: OpenOrchestra\BackofficeBundle\Form\Type\BlockType
    open_orchestra_backoffice.type.existing_block_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\ExistingBlockChoiceType
    open_orchestra_backoffice.type.orchestra_block.class: OpenOrchestra\BackofficeBundle\Form\Type\BlockChoiceType
    open_orchestra_backoffice.type.site.class: OpenOrchestra\BackofficeBundle\Form\Type\SiteType
    open_orchestra_backoffice.type.site_alias.class: OpenOrchestra\BackofficeBundle\Form\Type\SiteAliasType
    open_orchestra_backoffice.type.orchestra_content.class : OpenOrchestra\BackofficeBundle\Form\Type\ContentType
    open_orchestra_backoffice.type.content_type.class: OpenOrchestra\BackofficeBundle\Form\Type\ContentTypeType
    open_orchestra_backoffice.type.orchestra_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\OrchestraChoiceType
    open_orchestra_backoffice.type.status.class: OpenOrchestra\BackofficeBundle\Form\Type\StatusType
    open_orchestra_backoffice.type.field_type.class: OpenOrchestra\BackofficeBundle\Form\Type\FieldTypeType
    open_orchestra_backoffice.type.field_option.class: OpenOrchestra\BackofficeBundle\Form\Type\FieldOptionType
    open_orchestra_backoffice.type.choices_option.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\ChoicesOptionType
    open_orchestra_backoffice.type.field_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\FieldChoiceType
    open_orchestra_backoffice.type.date_widget_option.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\DateWidgetOptionType
    open_orchestra_backoffice.type.date_picker.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\DatePickerType
    open_orchestra_backoffice.type.translated_value.class: OpenOrchestra\BackofficeBundle\Form\Type\TranslatedValueType
    open_orchestra_backoffice.type.translated_value_collection.class: OpenOrchestra\BackofficeBundle\Form\Type\TranslatedValueCollectionType
    open_orchestra_backoffice.type.theme_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\ThemeChoiceType
    open_orchestra_backoffice.type.theme.class: OpenOrchestra\BackofficeBundle\Form\Type\ThemeType
    open_orchestra_backoffice.type.node_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\NodeChoiceType
    open_orchestra_backoffice.type.site_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\SiteChoiceType
    open_orchestra_backoffice.type.content_type_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\ContentTypeChoiceType
    open_orchestra_backoffice.type.content_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\ContentChoiceType
    open_orchestra_backoffice.type.tinymce.class: OpenOrchestra\BackofficeBundle\Form\Type\TinymceType
    open_orchestra_backoffice.type.keyword.class: OpenOrchestra\BackofficeBundle\Form\Type\KeywordType
    open_orchestra_backoffice.type.keywords_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\KeywordsChoiceType
    open_orchestra_backoffice.type.role.class: OpenOrchestra\BackofficeBundle\Form\Type\RoleType
    open_orchestra_backoffice.type.group.class: OpenOrchestra\BackofficeBundle\Form\Type\GroupType
    open_orchestra_backoffice.type.redirection.class: OpenOrchestra\BackofficeBundle\Form\Type\RedirectionType
    open_orchestra_backoffice.type.video.class: OpenOrchestra\BackofficeBundle\Form\Type\VideoType
    open_orchestra_backoffice.type.color_picker.class: OpenOrchestra\BackofficeBundle\Form\Type\ColorPickerType
    open_orchestra_backoffice.type.role_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\RoleChoiceType
    open_orchestra_backoffice.type.api_client.class: OpenOrchestra\BackofficeBundle\Form\Type\ApiClientType
    open_orchestra_backoffice.type.operator_choice.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\OperatorChoiceType
    open_orchestra_backoffice.type.content_search.class: OpenOrchestra\BackofficeBundle\Form\Type\Component\ContentSearchType

    open_orchestra_backoffice.tinymce:
        tinymce_jquery: false
        include_jquery: false
        selector: .tinymce
        theme:
            simple:
                theme: modern
                content_css: /built/openorchestrabackoffice/css/tinyMCEPatches/floatPanel.css
                plugins:
                    - advlist autolink lists link image charmap print preview hr anchor pagebreak
                    - searchreplace wordcount visualblocks visualchars code fullscreen
                    - insertdatetime media nonbreaking save table contextmenu directionality
                    - emoticons template paste textcolor orchestra_bbcode
                toolbar1: undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link
                toolbar2: forecolor backcolor
                menubar: false
                height: 200

services:
    # Template form type
    open_orchestra_backoffice.type.template:
        class: %open_orchestra_backoffice.type.template.class%
        arguments:
            - %open_orchestra_model.document.template.class%
            - %open_orchestra_model.document.area.class%
            - @translator
        tags:
            - { name: form.type, alias: oo_template }
    # Node form type
    open_orchestra_backoffice.type.node:
        class: %open_orchestra_backoffice.type.node.class%
        arguments:
            - %open_orchestra_model.document.node.class%
            - @open_orchestra_model.repository.template
            - @open_orchestra_model.repository.site
            - @open_orchestra_backoffice.manager.node
            - %open_orchestra_model.document.area.class%
            - @translator
        tags:
            - { name: form.type, alias: oo_node }
    # Area form type
    open_orchestra_backoffice.type.area:
        class: %open_orchestra_backoffice.type.area.class%
        arguments:
            - %open_orchestra_model.document.area.class%
            - @translator
        tags:
            - { name: form.type, alias: oo_area }
    # Block form type
    open_orchestra_backoffice.type.block:
        class: %open_orchestra_backoffice.type.block.class%
        arguments:
            - @open_orchestra_backoffice.generate_form_manager
            - %open_orchestra_backoffice.block.fixed_attributes%
            - @form.factory
        tags:
            - { name: form.type, alias: oo_block }
    open_orchestra_backoffice.type.existing_block_choice:
        class: %open_orchestra_backoffice.type.existing_block_choice.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: form.type, alias: oo_existing_block }

    open_orchestra_backoffice.type.orchestra_block:
        class: %open_orchestra_backoffice.type.orchestra_block.class%
        arguments:
            - %open_orchestra.blocks%
        tags:
            - { name: form.type, alias: oo_block_choice }
    # Site Form Builder
    open_orchestra_backoffice.type.site:
        class: %open_orchestra_backoffice.type.site.class%
        arguments:
            - %open_orchestra_model.document.site.class%
            - @translator
        tags:
            - { name: form.type, alias: oo_site }
    open_orchestra_backoffice.type.site_alias:
        class: %open_orchestra_backoffice.type.site_alias.class%
        arguments:
            - %open_orchestra_model.document.site_alias.class%
        tags:
            - { name: form.type, alias: oo_site_alias }
    # Content Type Form Builder
    open_orchestra_backoffice.type.content_type:
        class: %open_orchestra_backoffice.type.content_type.class%
        arguments:
            - %open_orchestra_model.document.content_type.class%
            - @translator
            - @open_orchestra_backoffice.listener.translate_value_initializer
        tags:
            - { name: form.type, alias: oo_content_type }
    open_orchestra_backoffice.type.field_type:
        class: %open_orchestra_backoffice.type.field_type.class%
        arguments:
            - @open_orchestra_backoffice.listener.translate_value_initializer
            - %open_orchestra_backoffice.field_types%
            - %open_orchestra_model.document.field_option.class%
            - %open_orchestra_model.document.field_type.class%
            - %open_orchestra_backoffice.field_types%
        tags:
            - { name: form.type, alias: oo_field_type }
    open_orchestra_backoffice.type.field_option:
        class: %open_orchestra_backoffice.type.field_option.class%
        arguments:
            - %open_orchestra_backoffice.options%
            - %open_orchestra_model.document.field_option.class%
        tags:
            - { name: form.type, alias: oo_field_option }
    open_orchestra_backoffice.type.choices_option:
        class: %open_orchestra_backoffice.type.choices_option.class%
        arguments:
            - @open_orchestra_backoffice.transformer.choices_option_to_array
        tags:
            - { name: form.type, alias: oo_choices_option}
    open_orchestra_backoffice.type.field_choice:
        class: %open_orchestra_backoffice.type.field_choice.class%
        arguments:
            - @open_orchestra_backoffice.transformer.choice_array_to_string
            - @open_orchestra_backoffice.transformer.choice_string_to_array
        tags:
            - { name: form.type, alias: oo_field_choice}
    open_orchestra_backoffice.type.date_widget_option:
        class: %open_orchestra_backoffice.type.date_widget_option.class%
        tags:
            - { name: form.type, alias: oo_date_widget_option}
    open_orchestra_backoffice.type.date_picker:
        class: %open_orchestra_backoffice.type.date_picker.class%
        tags:
            - { name: form.type, alias: oo_date_picker}

    # Status Type
    open_orchestra_backoffice.type.status:
        class: %open_orchestra_backoffice.type.status.class%
        arguments:
            - %open_orchestra_model.document.status.class%
            - @open_orchestra_backoffice.listener.translate_value_initializer
        tags:
            - { name: form.type, alias: oo_status }

    # Content Form Builder
    open_orchestra_backoffice.type.orchestra_content:
        class: %open_orchestra_backoffice.type.orchestra_content.class%
        arguments:
            - @open_orchestra_backoffice.subscriber.content_type
            - %open_orchestra_model.document.content.class%
        tags:
            - {name: form.type, alias: oo_content}

    # Language form field type
    open_orchestra_backoffice.type.language:
        class: %open_orchestra_backoffice.type.orchestra_choice.class%
        arguments:
            - %open_orchestra_backoffice.orchestra_choice.front_language%
            - "orchestra_language"
        tags:
            - { name: form.type, alias: orchestra_language }

    # Direction form field type
    open_orchestra_backoffice.type.direction:
        class: %open_orchestra_backoffice.type.orchestra_choice.class%
        arguments:
            - %open_orchestra_backoffice.orchestra_choice.direction%
            - "orchestra_direction"
        tags:
            - { name: form.type, alias: orchestra_direction }

    open_orchestra_backoffice.type.translated_value:
        class: %open_orchestra_backoffice.type.translated_value.class%
        arguments:
            - %open_orchestra_model.document.translated_value.class%
            - %open_orchestra_base.administration_languages%
        tags:
            - { name: form.type, alias: oo_translated_value }
    open_orchestra_backoffice.type.translated_value_collection:
        class: %open_orchestra_backoffice.type.translated_value_collection.class%
        tags:
            - { name: form.type, alias: oo_translated_value_collection }
    open_orchestra_backoffice.type.theme_choice:
        class: %open_orchestra_backoffice.type.theme_choice.class%
        arguments:
            - @open_orchestra_model.repository.theme
        tags:
            - { name: form.type, alias: oo_theme_choice}
    open_orchestra_backoffice.type.theme:
        class: %open_orchestra_backoffice.type.theme.class%
        arguments:
            - %open_orchestra_model.document.theme.class%
        tags:
            - { name: form.type, alias: oo_theme}
    open_orchestra_backoffice.type.node_choice:
        class: %open_orchestra_backoffice.type.node_choice.class%
        arguments:
            - @open_orchestra_model.repository.node
            - @open_orchestra_display.manager.tree
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: form.type, alias: oo_node_choice}
    open_orchestra_backoffice.type.site_choice:
        class: %open_orchestra_backoffice.type.site_choice.class%
        arguments:
            - @open_orchestra_model.repository.site
        tags:
            - { name: form.type, alias: oo_site_choice}
    open_orchestra_backoffice.type.content_type_choice:
        class: %open_orchestra_backoffice.type.content_type_choice.class%
        arguments:
            - @open_orchestra_model.repository.content_type
            - @open_orchestra_backoffice.context_manager
        tags:
            - { name: form.type, alias: oo_content_type_choice}
    open_orchestra_backoffice.type.content_choice:
        class: %open_orchestra_backoffice.type.content_choice.class%
        arguments:
            - @open_orchestra_model.repository.content
            - @open_orchestra_backoffice.context_manager
            - @open_orchestra_backoffice.transformer.reference_to_embed
            - content
        tags:
            - { name: form.type, alias: oo_content_choice}
    open_orchestra_backoffice.type.orchestra_color_choice:
        class: %open_orchestra_backoffice.type.orchestra_choice.class%
        arguments:
            - %open_orchestra_backoffice.choice.available_color%
            - "orchestra_color_choice"
        tags:
            - { name: form.type, alias: orchestra_color_choice}
    open_orchestra_backoffice.type.orchestra_frequence_choice:
        class: %open_orchestra_backoffice.type.orchestra_choice.class%
        arguments:
            - %open_orchestra_backoffice.choice.frequence%
            - "orchestra_frequence_choice"
        tags:
            - { name: form.type, alias: orchestra_frequence_choice}
    open_orchestra_backoffice.type.tinymce:
        class: %open_orchestra_backoffice.type.tinymce.class%
        arguments:
            - @open_orchestra_backoffice.transformer.bbcode_to_html
        tags:
            - { name: form.type, alias: oo_tinymce}
    open_orchestra_backoffice.type.keyword:
        class: %open_orchestra_backoffice.type.keyword.class%
        tags:
            - { name: form.type, alias: oo_keyword}
    open_orchestra_backoffice.type.keywords_choice:
        class: %open_orchestra_backoffice.type.keywords_choice.class%
        arguments:
            - @open_orchestra_backoffice.transformer.embedkeywords_to_keywords
            - @open_orchestra_model.repository.keyword
            - @router
            - @security.authorization_checker
        tags:
            - { name: form.type, alias: oo_keywords_choice}
    open_orchestra_backoffice.type.role:
        class: %open_orchestra_backoffice.type.role.class%
        arguments:
            - @open_orchestra_backoffice.listener.translate_value_initializer
            - %open_orchestra_model.document.role.class%
        tags:
            - { name: form.type, alias: oo_role }
    open_orchestra_backoffice.type.group:
        class: %open_orchestra_backoffice.type.group.class%
        arguments:
            - %open_orchestra_user.document.group.class%
            - @open_orchestra_backoffice.listener.translate_value_initializer
        tags:
            - { name: form.type, alias: oo_group }
    open_orchestra_backoffice.type.redirection:
        class: %open_orchestra_backoffice.type.redirection.class%
        arguments:
            - %open_orchestra_model.document.redirection.class%
        tags:
            - { name: form.type, alias: oo_redirection }
    open_orchestra_backoffice.type.video:
        class: %open_orchestra_backoffice.type.video.class%
        arguments:
            - @open_orchestra_backoffice.transformer.video_url_to_id
        tags:
            - { name: form.type, alias: oo_video }
    open_orchestra_backoffice.type.color_picker:
        class: %open_orchestra_backoffice.type.color_picker.class%
        tags:
            - { name: form.type, alias: oo_color_picker }
    open_orchestra_backoffice.type.role_choice:
        class: %open_orchestra_backoffice.type.role_choice.class%
        arguments:
            - @open_orchestra_backoffice.collector.backoffice_role
            - oo_role_choice
        tags:
            - { name: form.type, alias: oo_role_choice }
    open_orchestra_backoffice.type.front_role_choice:
        class: %open_orchestra_backoffice.type.role_choice.class%
        arguments:
            - @open_orchestra_backoffice.collector.front_role
            - oo_front_role_choice
        tags:
            - { name: form.type, alias: oo_front_role_choice }
    open_orchestra_backoffice.type.api_client:
        class: %open_orchestra_backoffice.type.api_client.class%
        arguments:
            - %open_orchestra_api.document.api_client.class%
        tags:
            - { name: form.type, alias: oo_api_client }
    open_orchestra_backoffice.type.operator_choice:
        class: %open_orchestra_backoffice.type.operator_choice.class%
        tags:
            - { name: form.type, alias: oo_operator_choice}
    open_orchestra_backoffice.type.content_search:
        class: %open_orchestra_backoffice.type.content_search.class%
        arguments:
            - %open_orchestra.transformer.boolean_to_bdd.class%
        tags:
            - { name: form.type, alias: oo_content_search}
