parameters:
    open_orchestra_model.validatorcontent_template.class: OpenOrchestra\Backoffice\Validator\Constraints\ContentTemplateValidator
    open_orchestra_model.validator.block_node_pattern.class: OpenOrchestra\Backoffice\Validator\Constraints\BlockNodePatternValidator
    open_orchestra_model.validator.restore_node.class: OpenOrchestra\Backoffice\Validator\Constraints\RestoreNodeValidator
    open_orchestra_model.validator.unique_area_id.class: OpenOrchestra\Backoffice\Validator\Constraints\UniqueAreaIdValidator
    open_orchestra_model.validator.unique_node_order.class: OpenOrchestra\Backoffice\Validator\Constraints\UniqueNodeOrderValidator
    open_orchestra_model.validator.area_flex_row_layout.class: OpenOrchestra\Backoffice\Validator\Constraints\AreaFlexRowLayoutValidator
    open_orchestra_model.validator.check_variable_route_pattern_in_menu.class: OpenOrchestra\Backoffice\Validator\Constraints\CheckVariableRoutePatternInMenuValidator
    open_orchestra_model.validator.role_statuses.class: OpenOrchestra\Backoffice\Validator\Constraints\RoleStatusesValidator
    open_orchestra_model.validator.trashitem_remove_node.class: OpenOrchestra\Backoffice\Validator\Constraints\TrashcanRemoveNodeValidator
    open_orchestra_model.validator.boolean_condition.class: OpenOrchestra\Backoffice\Validator\Constraints\BooleanConditionValidator

services:
    open_orchestra_model.validatorcontent_template:
        class: %open_orchestra_model.validatorcontent_template.class%
        arguments:
            - @twig
        tags:
            - { name: validator.constraint_validator, alias: content_template}
    open_orchestra_model.validator.block_node_pattern:
        class: %open_orchestra_model.validator.block_node_pattern.class%
        arguments:
            - @open_orchestra_backoffice.generate_form_manager
        tags:
            - { name: validator.constraint_validator, alias: block_node_pattern}
    open_orchestra_model.validator.restore_node:
        class: %open_orchestra_model.validator.restore_node.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: validator.constraint_validator, alias: restore_node}
    open_orchestra_model.validator.unique_area_id:
        class: %open_orchestra_model.validator.unique_area_id.class%
        tags:
            - { name: validator.constraint_validator, alias: unique_area_id}
    open_orchestra_model.validator.unique_node_order:
        class: %open_orchestra_model.validator.unique_node_order.class%
        arguments:
            - @open_orchestra_model.repository.node
        tags:
            - { name: validator.constraint_validator, alias: unique_node_order}
    open_orchestra_model.validator.area_flex_row_layout:
        class: %open_orchestra_model.validator.area_flex_row_layout.class%
        tags:
            - { name: validator.constraint_validator, alias: area_flex_row_layout}
    open_orchestra_model.validator.check_variable_route_pattern_in_menu:
        class: %open_orchestra_model.validator.check_variable_route_pattern_in_menu.class%
        tags:
            - { name: validator.constraint_validator, alias: check_variable_route_pattern_in_menu}
    open_orchestra_model.validator.role_statuses:
        class: %open_orchestra_model.validator.role_statuses.class%
        arguments:
            - @open_orchestra_model.repository.role
        tags:
            - { name: validator.constraint_validator, alias: role_statuses}
    open_orchestra_model.validator.trashitem_remove_node:
        class: %open_orchestra_model.validator.trashitem_remove_node.class%
        tags:
            - { name: validator.constraint_validator, alias: remove_node_date}
    open_orchestra_model.validator.boolean_condition:
        class: %open_orchestra_model.validator.boolean_condition.class%
        tags:
            - { name: validator.constraint_validator, alias: boolean_condition}
